[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.4.0",
    "pytest>=8.4.2",
    "typer>=0.16.0",
    "typer_shell>=1.0.3",
]
